server:
  port: 8888

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9494/auth/realms/t1
          jwk-set-uri: http://localhost:9494/auth/realms/t1/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:25401/dbname
    password: password
    username: user


  jackson:
    property-naming-strategy: SNAKE_CASE