version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - md-kafka-network
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=EXTERNAL
      - KAFKA_CFG_ADVERTISED_HOST_NAME=localhost
    depends_on:
      - zookeeper
    networks:
      - md-kafka-network

  kafka-web-ui:
    image: 'obsidiandynamics/kafdrop:latest'
    ports:
      - '9999:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    #      - JVM_OPTS='-Xms32M -Xmx64M'
    depends_on:
      - kafka
    networks:
      - md-kafka-network


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  md-kafka-network:
    driver: bridge