spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9494/auth/realms/t1
        registration:
          keycloak:
            client-id: c1
            client-secret: c6d9677c-2639-46d6-b06e-c773a146088b
            scope: offline_access,profile,email,address,phone,roles,web-origins,microprofile-jwt

  cloud:
    gateway:
      default-filters:
        - TokenRelay

      routes:
        - id: family-service
          uri: http://localhost:8888
          predicates:
            - Path=/api/family-service/**
          filters:
            - RewritePath=/api/family-service(?<segment>/?.*), $\{segment}